# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 18:49
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    User.objects.create_superuser('admin', 'admin@teste.com', 'admin123')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
        ),
        migrations.RunPython(forwards_func),
    ]
