# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(max_length=4, verbose_name='ano'),
        ),
    ]
